### ISSUE TITLE
DGX Nightly Benchmark run 20210315

### ISSUE THREAD

**Issue by quasiben** [quasiben/dask-scheduler-performance#127]
## Benchmark history
<img width="641" alt="Benchmark Image"
src="https://raw.githubusercontent.com/quasiben/dask-scheduler-performance/benchmark-images/assets/dgx-20210315-benchmark-history.png">

## Raw Data
<Client: 'tcp://127.0.0.1:37063' processes=10 threads=10, memory=540.94 GB>
Distributed Version: 2021.03.0+9.g4ce8c650
simple
	 4.838e-01 +/- 1.001e-01
shuffle
	 2.282e+01 +/- 1.155e+00
rand_access
	 1.028e-02 +/- 1.147e-03
anom_mean
	 1.05e+02 +/- 2.762e+01

## Raw Values
simple
	 [0.57867479 0.55036449 0.33823133 0.51130247 0.50777626 0.56569362
 0.5178597  0.26232481 0.56047106 0.4449563 ]
shuffle
	 [23.62676001 20.59953952 22.51121664 22.72051716 23.01530981 24.41906452
 21.38436341 22.1112802  24.19957256 23.5877161 ]
rand_access
	 [0.00789547 0.01067019 0.00949192 0.01251531 0.00966954 0.01079416
 0.01043701 0.01049185 0.0110929  0.00969577]
anom_mean
	 [113.61392879 114.61251688 113.57071495 113.06654763 116.32618928
 111.62947464 112.11603189  22.23330307 116.84015632 115.5072813 ]

## Dask Profiles

- [Shuffle
 Profile](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/20210315-shuffle-scheduler.html)
- [Random Access
  Profile](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/20210315-rand-access-scheduler.html)
- [Simple
  Profile](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/20210315-simple-scheduler.html)
- [Anom
  Mean](https://raw.githack.com/quasiben/dask-scheduler-performance/benchmark-images/assets/20210315-anom-mean-scheduler.html)

## Scheduler Execution Graph
<img width="641" alt="Sched Graph Image"
src="https://raw.githubusercontent.com/quasiben/dask-scheduler-performance/benchmark-images/assets/20210315-sched-graph.png">

**Comment by jakirkham** [comment]
When I run this locally, I'm getting a different result. In particular `reevaluate_occupancy` is taking an equivalent amount of time as `_transition`. However the DGX run shows `reevaluate_occupancy` little to no time. The DGX result use to show a similar result however that changed 1 week ago without any changes to Distributed ( https://github.com/quasiben/dask-scheduler-performance/issues/121#issuecomment-793104140 ). Given this am curious if something has changed about how the benchmark is being run. @quasiben do you have any insights here? 🙂

![prof_95744 pstat dot](https://user-images.githubusercontent.com/3019665/111210126-1b9a2500-858a-11eb-93a6-48cb68b13f3d.png)

**Comment by quasiben** [comment]
There were some issues with running `uvloop` instead of tornado but that was resolved a few weeks ago.  Recall the config now looks like the following:

```yaml
distributed:
  version: 2
  worker:
    profile:
      interval: 10s        # Time between statistical profiling queries
      cycle: 1000s         # Time between starting new profile
      low-level: False      # Whether or not to include low-level functions
  admin:
    event-loop: uvloop
    system-monitor:
      interval: 1h
```

**Comment by jakirkham** [comment]
Can you please share a bit more about the issue with `uvloop`? We seem to still see this even in the latest run. So it is likely still happening with some reliability (if that is the cause)

**Comment by quasiben** [comment]
The uvloop issue was with cleanup in the dask-cuda-benchmark nightly runs.  But it did result in me fiddling with the shared config.
